// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Returns the correct configuration based on which platform the app is running on
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return Web config if running in a browser
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // Return Android config for mobile
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows; // Return Windows config for desktop debugging
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configuration for Web Apps
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFO9IsXcAjv5Ay1fcMmq1kflHJHqXuIu4',
    appId: '1:792079455443:web:720bb720bb720bb720bb', 
    messagingSenderId: '792079455443',
    projectId: 'small-store-720bb',
    authDomain: 'small-store-720bb.firebaseapp.com',
    storageBucket: 'small-store-720bb.firebasestorage.app',
  );

  // Configuration for Android Apps
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFO9IsXcAjv5Ay1fcMmq1kflHJHqXuIu4',
    appId: '1:792079455443:android:85a6a6fa471f66fde4f026',
    messagingSenderId: '792079455443',
    projectId: 'small-store-720bb',
    storageBucket: 'small-store-720bb.firebasestorage.app',
  );

  // Configuration for Windows Desktop
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFO9IsXcAjv5Ay1fcMmq1kflHJHqXuIu4',
    appId: '1:792079455443:windows:720bb720bb720bb720bb',
    messagingSenderId: '792079455443',
    projectId: 'small-store-720bb',
    authDomain: 'small-store-720bb.firebaseapp.com',
    storageBucket: 'small-store-720bb.firebasestorage.app',
  );
}

